add minesweeper game
lenormf/kakoune-extra pull request #3
Opened 2017-02-09 18:39 UTC by occivink

Turns out I didn't need this `raise` command you mentioned. The recursion limit is sometimes hit in extreme cases, but I didn't find an iterative way to uncover adjacent safe squares.

2017-02-10 06:20 UTC, lenormf requested changes
Nice! I haven't tried the script yet, but here are some remarks about the code.

2017-02-10 06:20 UTC, lenormf commented on games/minesweeper.kak
> +    exec %sh{ printf %d $(($1 * $2)) }O<space><esc>gjdgg %arg{3} JK<a-s>Hrx\%|shuf<ret>
`shuf` is a GNU coreutils utility, maybe you could use an -ugly- `awk` [based solution](http://stackoverflow.com/a/30133294)?

2017-02-10 06:20 UTC, lenormf commented on games/minesweeper.kak
> +    exec '%"my'
Since we're using registers here, it'd be good to put the function in a draft to avoid spoiling the parent context.

2017-02-10 06:20 UTC, lenormf commented on games/minesweeper.kak
> +    add-highlighter -group minesweeper regex '!' 0:black,yellow
These will fail if a `*minesweeper*` buffer has already been open.

2017-02-10 06:20 UTC, lenormf commented on games/minesweeper.kak
> +def minesweeper_toggle_flag %{
Is there a reason why this function isn't hidden?

2017-02-10 06:20 UTC, lenormf commented on games/minesweeper.kak
> +        exec '"my'
Global register modified.

2017-02-10 06:20 UTC, lenormf commented on games/minesweeper.kak
> +def minesweeper_check %{
Not hidden either.

2017-02-10 09:22 UTC, occivink commented
The functions that are not hidden are the user-facing ones, as opposed to the other that are implementation details. But I suppose that since they're mapped, they don't need to be visible.

2017-02-10 09:35 UTC, occivink commented on games/minesweeper.kak
> +    add-highlighter -group minesweeper regex '!' 0:black,yellow
I have `try %{ minesweeper_quit }` at the beginning of the command for that. In any case, I've checked that you can restart a game if one is already open.

2017-02-10 09:44 UTC, lenormf commented
Yes, I would expect the only command to be visible be `minesweeper`.

2017-02-10 12:12 UTC, occivink commented
This should address your remarks, plus some cosmetics and readability changes.

2017-02-11 15:29 UTC, lenormf approved these changes

2017-02-11 15:29 UTC, merged